### ISSUE TITLE
Completed module 2 assignments

### ISSUE THREAD

**Issue by jonathanoti** [ds4owd-001/md-02-assignments-jonathanoti#1]
Do I need to stick strictly to the methods taught in the workshop for the assignments? @larnsce @mianzg @sskorik01

**Comment by larnsce** [comment]
Well done, @jonathanoti. The assignment looks complete.

I recommend you practice writing the syntax that we teach, but you are of course free to use which ever syntax you prefer. Do you have experience in writing base R syntax? Or do you mean something else by "methods"?

**Comment by jonathanoti** [comment]
Thank you for the feedback @larnsce. Yes I do have some experience with base R syntax.

**Comment by larnsce** [comment]
That is great. It will help you a lot. I will close the issue now.
